### PR TITLE
Add macOS app KimaiBar

### PR DESCRIPTION
**Pull request by ChaosCoder**
This adds the macOS menu bar app KimaiBar to the marketplace.
More information on [kimaibar.app](https://kimaibar.app)

### CODE REVIEW

**Comment by kevinpapst** [comment]
Can you please update your websites font to NOT load from fontawesome.com

Lets try to stand by what we say 😁 
Bildschirm­foto 2023-03-10 um 18 55 10

Meanwhile: thank you, I'll review asap.

**Comment by ChaosCoder** [comment]
> Can you please update your websites font to NOT load from fontawesome.com

Done. 😉

**Comment by ChaosCoder** [comment]
> Meanwhile: thank you, I'll review asap.

Any update on this, @kevinpapst? Or some details about what "asap" means? We can't wait to be officially listed in the Kimai marketplace 🤩

**Comment by kevinpapst** [comment]
I understand. My inbox is flooded and I am just one person.

What about sharing a license key, so I can test it?
Have you already tested the next major version? Is the API compatible?

**Comment by kevinpapst** [comment]
And one more: can you please share your icon version with https://github.com/kimai/images

I don't mean the button. 
But only the pure round Kimai icon with the slightly adjusted green colors and the removed hour markers as single icon.
If you have it as vector image.

**Comment by ChaosCoder** [comment]
> Have you already tested the next major version? Is the API compatible?

We have not yet. We have it on our roadmap though.

> Please edit the PR and change the permissions to allow pushes from the maintainer. Otherwise I can't merge.

This PR is from a organization account so there is no option to allow changes from maintainers… (at least that's how we interpret https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork). Can you send me a patch instead (email)?

> What about sharing a license key, so I can test it?

You will receive an email soon. 👍🏻

**Comment by kevinpapst** [comment]
Never heard abou such an inconvenient limitation. 
Sure? If you Edit the PR (not the initial post).
How does the screen look like, can you share a screenshot?

Please, patches through email... this is neither the Linux kernel nor year 2000 😁 
I will merge directly if it doesn't work through GitHub.

**Comment by kevinpapst** [comment]
I merged manually.

Thanks @ChaosCoder 👍

**Pull request closed without merging**
