### PR TITLE
docs: update kimai_2_version to 2.0.30

### PR DESCRIPTION
**Pull request by cngJo**

### CODE REVIEW

**Comment by kevinpapst** [comment]
Thanks @cngJo 👍

**Comment by cngJo** [comment]
@kevinpapst you're welcome

Would you be interested in an automated approach for this? 
E.g. a nightly GitHub Actions Job that fetched the latest release from `kimai/kimai` matching `2.x.x` and creating a pull request for the changes?

If so, I'd create a separate Ticket and provide a Pull Request to discuss it further 😉

**Comment by kevinpapst** [comment]
Yes, I would ❤️ that!

I prepared a bit some minutes ago...

This triggers an event on a new release: https://github.com/kimai/kimai/blob/main/.github/workflows/website.yaml

Which then executes this job: https://github.com/kimai/www.kimai.org/blob/main/.github/workflows/version.yml

So we can get around the nightly job and the version will be updated immediately upon release.

For reference, I am using the same to trigger the docker builds:
See https://github.com/tobybatch/kimai2/blob/main/.github/workflows/kimai-release.yml#L42C8-L42C8

So if you can provide the code for the [version workflow](https://github.com/kimai/www.kimai.org/blob/main/.github/workflows/version.yml), that would be super cool

**Comment by cngJo** [comment]
Oh, I wasn't aware of that, but it's awesome 🤩 

I'll provide a PR implementing the logic in the workflow in this repository in the next days!

**Comment by cngJo** [comment]
Created PRs

- https://github.com/kimai/www.kimai.org/pull/287
- https://github.com/kimai/kimai/pull/4248

for the above mentioned changes.

**Pull request merged**
