### PR TITLE
Croatian translation

### PR DESCRIPTION
**Pull request by milotype**
Please inspect/check the following Croatian settings for:
- permalink:
- redirect_from:
I’m not a programmer so I don’t know how to go about it. If corrections are needed, please let me know what to do, or correct the settings yourself.

### CODE REVIEW

**Comment by milotype** [comment]
@kevinpapst If possible, make the website translations possible at **Hosted Weblate**, just as the project [Kimai - Time tracking](https://hosted.weblate.org/projects/kimai/) … maybe as a separate project "Kimai - Website" with the necessary components …

**Comment by kevinpapst** [comment]
@milotype thanks for the PR 👍 

Using Weblate is unfortunately not possible, due to technical circumstances.

Could you please have a look at these files as well:
https://github.com/kimai/www.kimai.org/blob/master/_data/trans.yml
https://github.com/kimai/www.kimai.org/blob/master/_data/trans-menu.yml

**Comment by milotype** [comment]
@kevinpapst Yes, I'll translate those files and will add them to my current commit #121 ...

I the mean time, can you please check or tell me what to do with those **options** in the header of my translated files:
- permalink:
- redirect_from:

The german, french and english files have differrent entries for those options in some files!?

**Review by kevinpapst — APPROVED** [review]
@milotype I adjusted your PR, fixed a couple of minor issues (like the redirect_from that you mentioned) and adjusted the layout to support Croatian in the menu. Super cool, thank you 👍 
Will be available in a couple of minutes on the website.

**Comment by kevinpapst** [comment]
Really awesome job, I have to repeat myself - you thought about everything!

**Pull request merged**
