### PR TITLE
New Documentation Azure SAML

### PR DESCRIPTION
**Pull request by lucienn3**
+ added steps to fully set up the SAML

### CODE REVIEW

**Comment by kevinpapst** [comment]
Thanks a lot 🎉 

Could you please add the images to this directory: https://github.com/kimai/www.kimai.org/tree/master/images/documentation

And then link them with
```
![Azure](/images/documentation/azure-saml-pic1.png "Some description")
```

**Comment by lucienn3** [comment]
Sure, could you verify the steps ? This should likely be also possible in the free version with the exact steps provided by me.

I will do that later. Currently on the road 🚗.

**Comment by kevinpapst** [comment]
Oh thats interesting. I have a free account, can't remember where, but I will find and test it in the next days.

**Comment by lucienn3** [comment]
@kevinpapst Please recheck :) It should be correct now and ready to be moved. 

I tried adding a URL to the small documentation, but it doesn't seem to work, please recheck.

**Review by kevinpapst — APPROVED** [review]
Haven't tested it, but looks great. Thank you for this contribution 👍

**Comment by lucienn3** [comment]
If you need some assistance with documentation, please let me know. Happy to spend a few hours contributing to this to better the chance of a bigger install base. BTW I have used Kimai v1 and loved it. Would love to give back especially since you guys actually brought it back in a way that makes it more usable than the design and technology of v1 haha.

**Pull request merged**
