### PR TITLE
Use composer create-project to start the project

### PR DESCRIPTION
**Pull request by simonschaufi**
Instead of cloning the git repo, use composer to initialize the project

### CODE REVIEW

**Comment by kevinpapst** [comment]
Without `--keep-vcs` updates would not be possible.

The other problem is that flex will changes both `composer.json` and `composer.lock`, which leads to problems in updates for all the inexperienced users. See https://github.com/symfony/flex/issues/440

**Comment by simonschaufi** [comment]
Oh ok, I was not aware of this. I was wondering why you fetch the repo via git as this is not best practise for a release. I was just comparing this with a laravel application: https://laravel.com/docs/7.x#installing-laravel Section "Via Composer Create-Project"

**Comment by kevinpapst** [comment]
I am not the biggest fan of git for the end-user installation as well, but the Flex stuff is currently blocking the change.

**Comment by kevinpapst** [comment]
Closing, won't be fixed due to explained reasons.

**Comment by stijnbernards** [comment]
Hi @kevinpapst ,

We're currently looking to implement Kimai for our internal time registration tool and I see you've chosen to stay with the git clone approach, which is quite blocking for us in my opinion.

I'm not seeing how the symfony/flex issues stops Kimai from being able to be initialised via composer create-project.

Could you please elaborate?

**Pull request closed without merging**
