### PR TITLE
Update installation.md

### PR DESCRIPTION
**Pull request by Bharat-B**

### CODE REVIEW

**Comment by kevinpapst** [comment]
Do you have application specific landing pages? 
Or at least an overview of all apps that you support?

If Kimai support it is not visible from the outside (eg you have landing pages for Wordpress and Magento) then how will user get to know about it?

**Comment by Bharat-B** [comment]
> Do you have application specific landing pages?
> Or at least an overview of all apps that you support?
> 
> If Kimai support it is not visible from the outside (eg you have landing pages for Wordpress and Magento) then how will user get to know about it?

https://cloudjiffy.com/blog/solutions/one-click-solutions/kimai-time-tracking-on-cloudjiffy/

We don't have a landing page, we feature all our one-click-soutions at our blog.

**Comment by kevinpapst** [comment]
Okay, can you please link the part of the sentence "is only a click of a button away" to this blog posting.
Then I will merge it

**Comment by Bharat-B** [comment]
> Okay, can you please link the part of the sentence "is only a click of a button away" to this blog posting.
> Then I will merge it

Done.

**Comment by kevinpapst** [comment]
Nice work, thanks for supporting Kimai!

**Pull request merged**
