### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Kimai - Time tracking/www.kimai.org](https://hosted.weblate.org/projects/kimai/website/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by kevinpapst** [comment]
@yarons thank you for your continuous support with translations ❤️ 

But I need to ask for a favor. I worked a lot this weekend to simplify translation of the website, without me having to fiddle in thousand files. That's why there popped up so many new translation keys for the www.kimai.org component.

Now I activated Chinese first, because it was 100% translated (at least before I added all the new keys :grin:). Next I wanted to enable Hebrew, but on the website I haven't had RTL support. So I added that tonight. And I added the Hebrew pages, but did not really activate them, because I wanted you to double check it before adding them to the language dropdown menu.

So here finally comes the question: 
Can you please check if everything looks correct at https://www.kimai.org/he/ and let me know which issues you see.

**Comment by yarons** [comment]
There are some small glitches but overall it looks great.
At the bottom it says: Made by GitHub @ Kevin Pepst 😆 (We can add an RLM character next to the @ symbol :)

**Comment by kevinpapst** [comment]
Hahaha, I didn't notice that one 😁 thanks for checking @yarons 

I tried to add a `<span dir="ltr">` around the links text and I tried to remove all whitespace, but it still looks wrong:

Bildschirm­foto 2023-01-24 um 13 53 51

What is a RLM symbol? How do I do that?
Could you do it? https://github.com/kimai/www.kimai.org/blob/main/_includes/footer.html#L16

**Comment by kevinpapst** [comment]
I added a workaround for the footer.  If you have a better idea, I'd like to hear it. But it seems to work now.

One more question: the pages which are not yet translated, like "About Kimai" - is it better to have them like this:
Bildschirm­foto 2023-01-24 um 15 54 15

Or ist it better to reset via `dir="ltr"` and display them in the "original direction":
Bildschirm­foto 2023-01-24 um 15 54 23

**Comment by yarons** [comment]
It just need some tweaking to work properly, I'll try to come up with something.

**Pull request merged**
