### PR TITLE
Add kubernetes install docs

### PR DESCRIPTION
**Pull request by jmhbnz**
This pull requests adds documentation to the `Installation` page covering deployment of Kimai to a Kubernetes cluster.

### CODE REVIEW

**Review by kevinpapst — APPROVED** [review]

**Comment by kevinpapst** [comment]
Thanks! Please make sure the fork doesn't disappear ;-)
Normally it would be better to link to the original repo, because people will likely go there anyways.

**Comment by kevinpapst** [comment]
Actually, after giving it a second thought, I am not entirely happy with the fork link.
I don't mind the link to your company, totally fine, but I'd like to link to your real repository.
The fork might get deleted or you simply forget to sync with your latest master... there is no good reason for two repos, right @jmhbnz ?

**Comment by jmhbnz** [comment]
Hey Kevin - Fair enough, I set it as a link to the org repo as I worked on this with a colleague and we thought it was better to live in the org than me personally.

I will update at my end to remove my personal and make the org repo the main one so there is no confusion! ✔

**Comment by kevinpapst** [comment]
Yes, perfect solution - thanks 👍

**Pull request merged**
