### PR TITLE
added HMR-IT as a new developer + added android offline tracker to store

### PR DESCRIPTION
**Pull request by hmr-it-jr**

### CODE REVIEW

**Comment by kevinpapst** [comment]
👍 
Just one question: 0,99€ vs 1,19€? I see this:
Bildschirmfoto 2019-08-20 um 11 48 54
I think we shuold display end-user prices.

**Comment by hmr-it-jr** [comment]
I've used the net price because in the store at your plugins there is written "excl. VAT", too.

grafik

grafik

Displaying end-user prices is complicated since the VAT varies from country to country - so which VAT is the right one?

**Comment by kevinpapst** [comment]
Don't want to risk any troubles here.
I think its always the VAT for the developers country, afaik that is how Gumroad calculates it.
From my understanding the 49€ for example are the end-user price.
I guess I need to check that `excl. VAT` again (good chance that it is a left over from a previous version).

**Comment by kevinpapst** [comment]
I'll merge it anyways and if I find out it needs to be changed, I'll do it later by myself.

**Comment by hmr-it-jr** [comment]
In Google Playstore you can select how you want the prices to be calculated:

1. app price incl. vat
or
2. app price excl. vat

So yes, if you need to change anything just do it.

**Comment by kevinpapst** [comment]
Hm, so it can be wrong no matter what I write there? Then maybe leaving the excl. VAT is the best option...

**Comment by hmr-it-jr** [comment]
> Hm, so it can be wrong no matter what I write there? Then maybe leaving the excl. VAT is the best option...

Yes since every country has its own vat rate [https://www.ricksteves.com/travel-tips/money/vat-rates-in-europe](https://www.ricksteves.com/travel-tips/money/vat-rates-in-europe) - so best is without vat.

**Pull request merged**
