### PR TITLE
Prepared store for a new, free Backup Plugin Bundle

### PR DESCRIPTION
**Pull request by mxgross**
Maybe it is to early to publish the bundle in the store yet. But you may wanne kind of review and test it. Especially the resulting backups were not tested yet.
It is my first Symfony Bundle, so it will be a little hacky.

### CODE REVIEW

**Comment by kevinpapst** [comment]
Awesome! Nice idea. I will open a discussion in your repo later on.
Just had a quick look and have some ideas/question.
Especially regarding the settings, which I'd like to see in the SystemConfiguration... but more in your repo.

**Comment by mxgross** [comment]
I fixed a typo in the screenshot file name and url. Feel free to open more issues in the EasyBackupBundle repository. I will try to move the Settings to the SystemConfiguration as you mentioned :)

**Comment by kevinpapst** [comment]
I am really busy right now, but I will asap.

**Comment by kevinpapst** [comment]
I didn't make it before holidays. 
Sorry that I didn't manage it before and that I keep you waiting.
I'll get back to you in about a week.

**Comment by kevinpapst** [comment]
Thanks @mxgross ! Looks very good, I just changed some typos and spellings.

Now I will merge this and finally have a look at the plugin itself.

**Comment by kevinpapst** [comment]
Clicked wrong button ;-)

Merged 🚀

**Pull request merged**
